# Generated by Django 4.2.6 on 2023-12-11 20:21

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер комментария')),
                ('comment_text', models.TextField(max_length=255, verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер рецепта')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title', unique=True, verbose_name='URL')),
                ('recipe_description', models.TextField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('img', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер шага')),
                ('step_description', models.TextField(blank=True, max_length=255, verbose_name='Шаг рецепта')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking_recipes.recipes')),
            ],
        ),
    ]
